/**
 * Shared institutional print/PDF layout for SMS Oriximiná.
 * All documents generated by the system use this template
 * to ensure consistent branding across screen, PDF, and print.
 */

// Logo is served from the assets folder — Vite inlines or hashes it.
// For print windows we reference via absolute URL from the origin.
import logoSrc from '@/assets/logo-sms.jpeg';

const resolveLogoUrl = (): string => {
  // If logoSrc is already absolute (starts with http or /), use as-is
  if (logoSrc.startsWith('http') || logoSrc.startsWith('/')) return logoSrc;
  return logoSrc;
};

/** Standard institutional CSS shared across all documents */
export const institutionalCSS = `
<style>
  @page { size: A4; margin: 15mm 12mm; }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif; padding: 24px; color: #1e293b; font-size: 11px; line-height: 1.5; }

  /* HEADER */
  .doc-header {
    display: flex; align-items: center; gap: 16px;
    padding: 16px 20px; margin-bottom: 16px;
    background: linear-gradient(135deg, #0c4a6e, #0369a1);
    border-radius: 8px; color: #fff;
    -webkit-print-color-adjust: exact; print-color-adjust: exact;
  }
  .doc-header img { width: 56px; height: 56px; border-radius: 10px; object-fit: cover; border: 2px solid rgba(255,255,255,.3); }
  .doc-header .header-text { flex: 1; }
  .doc-header h1 { font-size: 15px; font-weight: 700; letter-spacing: .3px; }
  .doc-header .subtitle { font-size: 10px; opacity: .85; margin-top: 2px; }
  .doc-header .doc-title { font-size: 13px; font-weight: 700; margin-top: 6px; text-transform: uppercase; letter-spacing: .5px; }
  .doc-header .emit-date { text-align: right; font-size: 9px; opacity: .75; white-space: nowrap; }

  /* META INFO BAR */
  .doc-meta {
    font-size: 10px; color: #64748b; padding: 8px 12px;
    background: #f8fafc; border: 1px solid #e2e8f0;
    border-radius: 6px; margin-bottom: 14px;
    display: flex; gap: 16px; flex-wrap: wrap;
  }
  .doc-meta strong { color: #334155; }

  /* SUMMARY CARDS */
  .summary { display: flex; gap: 8px; margin-bottom: 16px; flex-wrap: wrap; }
  .stat { background: #f0f9ff; border: 1px solid #bae6fd; padding: 8px 14px; border-radius: 8px; text-align: center; min-width: 85px; }
  .stat strong { display: block; font-size: 18px; color: #0369a1; }
  .stat small { font-size: 9px; color: #64748b; }

  /* SECTION TITLES */
  h2 { font-size: 13px; color: #0369a1; margin: 16px 0 8px; padding-bottom: 4px; border-bottom: 2px solid #e0f2fe; }

  /* TABLES */
  table { width: 100%; border-collapse: collapse; margin-bottom: 14px; page-break-inside: auto; }
  thead { display: table-header-group; }
  tr { page-break-inside: avoid; page-break-after: auto; }
  th, td { border: 1px solid #e2e8f0; padding: 5px 8px; text-align: left; font-size: 10px; }
  th { background: #f1f5f9; font-weight: 600; color: #334155; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  tr:nth-child(even) { background: #f8fafc; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

  /* FIELDS (comprovante / prontuário) */
  .content-block { max-width: 580px; margin: 0 auto; }
  .field { margin-bottom: 10px; }
  .field-label { font-size: 10px; text-transform: uppercase; color: #64748b; font-weight: 600; letter-spacing: .4px; }
  .field-value { font-size: 13px; margin-top: 2px; color: #1e293b; }

  /* SECTIONS (prontuário) */
  .section { margin-bottom: 14px; }
  .section-title { font-weight: 600; font-size: 11px; text-transform: uppercase; color: #0369a1; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin-bottom: 6px; }
  .section-content { font-size: 12px; line-height: 1.6; white-space: pre-wrap; min-height: 18px; }

  /* INFO GRID */
  .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 16px; padding: 12px; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; }
  .info-label { font-weight: 600; font-size: 10px; text-transform: uppercase; color: #64748b; }
  .info-value { font-size: 12px; color: #1e293b; }

  /* QR AREA */
  .qr-area { text-align: center; margin-top: 28px; padding: 18px; border: 1px dashed #cbd5e1; border-radius: 8px; background: #fafafa; }
  .qr-area p { font-size: 11px; color: #64748b; }
  .qr-area .code { font-size: 10px; color: #94a3b8; margin-top: 4px; font-family: monospace; }

  /* SIGNATURE */
  .signature { margin-top: 50px; text-align: center; }
  .signature-line { width: 280px; border-top: 1px solid #333; margin: 0 auto 6px; }
  .signature .name { font-size: 12px; font-weight: 600; }
  .signature .role { font-size: 10px; color: #64748b; }

  /* FOOTER */
  .doc-footer {
    margin-top: 30px; padding-top: 10px;
    border-top: 1px solid #e2e8f0;
    font-size: 9px; color: #94a3b8;
    display: flex; justify-content: space-between; align-items: center;
  }
  .doc-footer .institution { font-weight: 600; color: #64748b; }

  /* PRINT MEDIA */
  @media print {
    body { padding: 10px; }
    .doc-header { border-radius: 0; }
    .no-print { display: none !important; }
  }
</style>`;

/** Generate the standard document header HTML */
export function docHeader(title: string, extraRight?: string): string {
  const logo = resolveLogoUrl();
  const now = new Date().toLocaleString('pt-BR');
  return `
    <div class="doc-header">
      <img src="${logo}" alt="Logo SMS Oriximiná" />
      <div class="header-text">
        <h1>Secretaria Municipal de Saúde de Oriximiná</h1>
        <div class="subtitle">Sistema de Gestão em Saúde</div>
        <div class="doc-title">${title}</div>
      </div>
      <div class="emit-date">
        ${extraRight || ''}
        <div>Emitido em: ${now}</div>
      </div>
    </div>`;
}

/** Generate metadata bar */
export function docMeta(items: Record<string, string>): string {
  const entries = Object.entries(items).map(([k, v]) => `<strong>${k}:</strong> ${v}`).join(' &nbsp;|&nbsp; ');
  return `<div class="doc-meta">${entries}</div>`;
}

/** Generate the standard footer */
export function docFooter(extraInfo?: string): string {
  const now = new Date().toLocaleString('pt-BR');
  return `
    <div class="doc-footer">
      <div class="institution">SMS Oriximiná — Sistema de Gestão em Saúde</div>
      <div>${extraInfo || ''}</div>
      <div>${now}</div>
    </div>`;
}

/** Open a print window with full institutional layout */
export function openPrintDocument(title: string, body: string, meta?: Record<string, string>): void {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const metaHtml = meta ? docMeta(meta) : '';

  printWindow.document.write(`<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <title>${title} — SMS Oriximiná</title>
  ${institutionalCSS}
</head>
<body>
  ${docHeader(title)}
  ${metaHtml}
  ${body}
  ${docFooter()}
</body>
</html>`);
  printWindow.document.close();
  setTimeout(() => { printWindow.focus(); printWindow.print(); }, 400);
}
