
ALTER TABLE public.pacientes
  ADD COLUMN IF NOT EXISTS municipio text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS menor_idade boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS nome_responsavel text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS cpf_responsavel text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ubs_origem text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS profissional_solicitante text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tipo_encaminhamento text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS diagnostico_resumido text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS justificativa text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS data_encaminhamento text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS documento_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS tipo_condicao text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS mobilidade text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS usa_dispositivo boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tipo_dispositivo text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS comunicacao text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS comportamento text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS usa_equipamentos boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS equipamentos text[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS observacao_equipamentos text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS outro_servico_sus boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS transporte text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS turno_preferido text NOT NULL DEFAULT '';
